### ISSUE TITLE
[bounty] migrate Go backend to Node.js (CHF 800)

### ISSUE THREAD

**Issue by marc0olo** [aeternity/aepp-token-migration-backend-nodejs#1]
## About the bounty program
This is one of multiple bounties that are part of the new bounty program.

Learn more:
- https://blog.aeternity.com/enlist-for-the-%C3%A6rmy-%C3%A6-wants-you-161ae5d44b3d
- https://github.com/aeternity/bounties

## Introduction
Aeternity cares about the token holders and therefore made sure that every original ERC20 token holder is able to migrate the tokens to aeternity mainnet. It is a quite unique approach compared to other projects. A contract deployed on aeternity mainnet knows the root hash of a merkle tree containing all addresses that are eligible to migrate their tokens. By providing the correct data and a valid signed message of the recipient AE address signed with the private key of the original Ethereum address the migration can be performed in a very smooth and convenient way. The smart contract verifies the signature and releases the tokens if the provided data is correct.

## Background
The current backend of the Token Migration aepp is written in Go and in the past there have always been several issues for users with the migration - mainly caused by the backend. Meanwhile the Go SDK of aeternity isn't actively maintained anymore and the Go backend is broken after the Iris hardfork happened.

**Note**
- Most logic of the Go backend is still working well and the merkle tree data is accurate
- Fixing the Go backend shouldn't be a big deal but we want to have a rewrite in Node.js

## Goal
The goal is to rewrite the current Go implementation in Node.js using the JavaScript SDK so that the current deployment can be easily replaced with the new Node.js implementation.

## Requirements
- [ ] Written in TypeScript
- [ ] Automated merkle tree generation based on the token holders file **on startup** (if the database is empty)
    - The Go backend required to call `/owner` endpoint for every token holder to generate the merkle tree
- [ ] Reasonable environment configuration (re-use existing environment variables where it makes sense)
- [ ] API uses same endpoints (path, request body, response body) as current Go implementation and executes similar logic
    - [ ] If the merkle tree generation is successful the default route `/` should respond following data:
    ```json
   {"status":true,"tree":{"root":"E4DBC69BF2783B81B0423DA3F5B684C1D37CCFAE798474525C4001DB42C67669","length":21016}}
    ```
    - [ ] The `/owner` route can be omitted since the merkle tree should be generated on startup (no need for that endpoint anymore)
    - [ ] The state of a migrated address which is included in the response should always be checked via contract if it hasn't been migrated yet
         - The current Go backend always returns the data stored in the database which isn't 100% accurate because if somebody performs a token migration manually (e.g. using the snippet listed below). Thus this is very important.
    - [ ] If an address is successfully migrated this can be marked in the database so that future requests checking the migration state don't require 
- [ ] Reasonable logging (e.g. using winston)
- [ ] Meaningful README
- [ ] ISC license

## Bounty payout conditions
When the implementation is finished a pull request should be provided to this repository. It will be reviewed and the bounty will be payed if the PR is finally merged into this repository. Please be aware that we might request some changes.

## Reference
- Current Go implementation
  - https://github.com/aeternity/aepp-token-migration-backend
- Backend API
  - https://github.com/aeternity/aepp-token-migration-backend#there-are-several-routes-that-can-be-access
- Token Holders:
  - https://github.com/aeternity/aepp-token-migration-holders
- Merkle tree generation:
  - https://github.com/thepiwo/merkle-tree
- Smart Contract:
  - Address (mainnet): `ct_eJhrbPPS4V97VLKEVbSCJFpdA4uyXiZujQyLqMFoYV88TzDe6`
  - SourceCode (Iris compatible): https://github.com/aeternity/aepp-token-migration-smart-contract/blob/master/contracts/TokenMigration.aes
  - Interface: https://github.com/kryptokrauts/ae-snippets-nodejs/blob/main/contracts/TokenMigrationInterface.aes
- Node.js snippet (can be used to "manually" migrate right now)
  - https://github.com/kryptokrauts/ae-snippets-nodejs/blob/main/migrate_ae_erc-20_to_aeternity_mainnet.md

**Comment by VitalJeevanjot** [comment]
Hi Marco,

I would like to go for this bounty and complete it by the end of the month.

Sincerely, 
Jeevanjot Singh.

**Comment by marc0olo** [comment]
Hi @genievot, that sounds great!

Can you please name a date when you aim to finish the bounty? Then I can assign it to you. Please make a realistic assumption and notify me if you need more time.

We just need to know that so we don't leave the bounty open for a too long time period. Giving others the chance to submit the bounty if you don't find enough time for any reason ;-)

**Comment by VitalJeevanjot** [comment]
My proposed deadline is: **10 Sep 2021**

I will keep you notified of any newer updates.

**Comment by marc0olo** [comment]
Go ahead! The bounty is assigned to you! ;-)

**Comment by marc0olo** [comment]
how is it going @genievot? maybe you can already provide a DRAFT PR so that we can comment and give feedback ;-)

**Comment by VitalJeevanjot** [comment]
Thank you for asking Marco, I will provide an update on this soon.

**Comment by marc0olo** [comment]
closed via #2.

@genievot thanks for your contribution! please consult with @ErkanKanden how to claim your reward ;-)

**Comment by ErkanKanden** [comment]
@genievot congrats!! Please share your AE wallet address here to claim your reward and fill in this form: https://form.jotform.com/212515121575347

**Comment by VitalJeevanjot** [comment]
Thank you @ErkanKanden .
My AE Wallet Address is ak_QWxf7hEM8CFPi3SmWSNTByQDKE2E5fgntPbEDwi7xvfb7SWwY

**Comment by ErkanKanden** [comment]
@genievot here is your bounty reward :)
https://explorer.aeternity.io/transactions/th_2cMNbkZtQUXz86VvCU255pjvyg2Sz8qj7Y6KK6Ezh1frmiDRy1
